cd~
cd ~
mv Downloads/git-completion.bash.txt
mv Downloads/git-completion.bash.txt git-completion.bash
d:
D:
cd D:
mv Downloads/git-completion.bash.txt git-completion.bash
mv Downloads/git-completion.bash
cd ~
mv Downloads/git-completion.bash
mv Downloads/git-completion.bash.txt git-completion.bash
mv Downloads\git-completion.bash.txt git-completion.bash
mv Downloads/git-completion.bash.txt git-completion.bash
mv /e/Download/git-completion.bash.txt
mv /e/Download/git-completion.bash.txt git-completion.bash
mv/e/Download/git-completion.bash.txt git-completion.bash
mv E:\git-completion.bash.txt git-completion.txt
mv E:/git-completion.bash.txt git-completion.txt
mv E:/git-prompt.sh
mv E:/git-prompt.sh git-prompt.sh
mv E:/bash_profile_course .bash_profile
mv E:/bash_profile_course .bash_profile
mv E:/Downloads/bash_profile_course .bash_profile
mv E:\Download\bash_profile_course .bash_profile
mv E:/Download/bash_profile_course .bash_profile
# add ~/.bash_profile if needed for executing ~/.bashrc
if [ -e ~/.bashrc -a ! -e ~/.bash_profile -a ! -e ~/.bash_login -a ! -e ~/.profile ]; then   printf "\n\033[31mWARNING: Found ~/.bashrc but no ~/.bash_profile, ~/.bash_login or ~/.profile.\033[m\n\n";   echo "This looks like an incorrect setup.";   echo "A ~/.bash_profile that loads ~/.bashrc will be created for you."
  cat >~/.bash_profile <<-\EOF
	# generated by Git for Windows
	test -f ~/.profile && . ~/.profile
	test -f ~/.bashrc && . ~/.bashrc
	EOF
 fi
# add ~/.bash_profile if needed for executing ~/.bashrc
if [ -e ~/.bashrc -a ! -e ~/.bash_profile -a ! -e ~/.bash_login -a ! -e ~/.profile ]; then   printf "\n\033[31mWARNING: Found ~/.bashrc but no ~/.bash_profile, ~/.bash_login or ~/.profile.\033[m\n\n";   echo "This looks like an incorrect setup.";   echo "A ~/.bash_profile that loads ~/.bashrc will be created for you."
  cat >~/.bash_profile <<-\EOF
	# generated by Git for Windows
	test -f ~/.profile && . ~/.profile
	test -f ~/.bashrc && . ~/.bashrc
	EOF
 fi
cd ~
git config --global core.editor "'C:/Program Files/Sublime Text 3/sublime_text.exe' -n -w"
git config --global push.default upstream
git config --global merge.conflictstyle diff3
alias subl="C:/Program\ Files/Sublime\ Text\ 3/sublime_text.exe"
cd ~
mv git-completion.txt git-completion.bash
subl
cd asteroids
‰PNG

IHDRhVË÷_sRGB®ÎégAMA±üa	pHYsttÞfxÿ¥IDATx^Ìý…—Wº·—X­f”°@%V3˜™ÙÍbVƒí8Éd(™äÓIf2ÁÉ$™É„™ÄvÌØÌvæ¼ßßñÝ{—¤V·í$sÞsÞçYëZµJ%èn[uÕïÞTDŽÔð}PH¹xÀ9B/—!rdz…mù‡ÙðO!ðÛ¿ôÉð!R]8X 6‰L$aâªŽ0ï!*Â²ú‹6øOCç{Úž4Ç?Tø¨üä;å÷¿®|àªŸ×<ð„öä¯t'Ò%#jïÁÒCëów8äëô’:•¸¢Dì,Ø
subl .bash_profile
git clone https://github.com/udacity/pappu-pakia.git
cd pappu-pakia
git log
git checkout 547f4171a82ec6429d002c1acef357aec41d3f17
git checkout 71d52709ddc4066e7a79a1d0a412e43429a0cdeb
git checkout fa4c6bade4970c282b3870ad16f1bde8164663a9
git log
git diff 71d527 547f41
git checkout 71d5
git checkout fa4c6ba
git log
git checkout 71d5
git commit
git stash
cd pappu-pakia
git log
 003c8c197cd3b1e5b28b58f53ee14d7ebaa9bb3a
git checkout 746f762 
gif diff 746f76 00
gif diff 746f76 003c8c
git diff 746f76 003c8c
subl
cd recipes
# Make sure that exactly one argument was given
if [ $# -ne 1 ]; then     if [ $# -gt 1 ]; then         echo "$0: Got more arguments than expected.  Expected exactly 1.";     else         echo "$0: Did not receive enough arguments.  Expected exactly 1.";     fi;      echo "Usage: bash $0 <GitHub url>";     exit; fi
cd recipes
subl
git branch canola-oil
git branch
git checkout canola-oil
subl chili-recipe.txt
subl cake-recipe.txt
git  status
git add cake-recipe.txt
git commit -m "Change oil to canola"
git push
git push origin canola-oil
cd ~
cd /E:
cd e:
cd downloads
cd downloads
cd /downloads
cd Downloads
cd e:/downloads
subl
login
cd D:
cd version-control
git status
git add
git add git_komandos.txt
git add -a
git add -A
git status
git commit -m "papylditi"
git push
git push master
git push origin master
cd version-control
cd asteroids
cd log
git log
git checkout 25ede
git log
git checkout a3c0a
git log
git checkout fe7993
git checkout
git log
touch index.html
touch app.js
touch init
git init
git config --global user.name 'Edgaras Komarovicius'
git add inder.html
git add index.html
git status
git --login
--login
login
git add.
git add .
git status
subl index.html
git status
git add .
git commit -m "Initial commit"
git status
git remote
git remote :
git branch
git remote add origin https://github.com/EdgarasKoma/asdf.git
git remote
